# Generated by Django 4.2.4 on 2024-02-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='description',
            field=models.CharField(db_index=True, help_text='Path description', max_length=1024),
        ),
        migrations.AlterField(
            model_name='path',
            name='headline',
            field=models.CharField(db_index=True, help_text='Path headline', max_length=512),
        ),
    ]
