# Generated by Django 4.2.4 on 2024-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_headline'),
        ('projects', '0002_alter_project_description_alter_project_name'),
        ('paths', '0002_alter_path_description_alter_path_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Career path courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='path',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Career path projects', to='projects.project'),
        ),
    ]
