# Generated by Django 4.2.4 on 2024-02-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_alter_path_courses_alter_path_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='image',
            field=models.ImageField(blank=True, help_text='Path image', null=True, upload_to='images/paths/'),
        ),
    ]
