# Generated by Django 4.2.4 on 2024-02-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='Project description', max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, help_text='Project name', max_length=64, unique=True),
        ),
    ]
