# Generated by Django 4.2.4 on 2024-02-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(help_text='Module description', max_length=1024),
        ),
    ]
