# Generated by Django 4.2.4 on 2024-01-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Course image', upload_to='images/courses/')),
                ('name', models.CharField(db_index=True, help_text='Course name', max_length=64, unique=True)),
                ('headline', models.CharField(db_index=True, help_text='Course headline', max_length=128)),
                ('description', models.CharField(db_index=True, help_text='Course description', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date updated')),
                ('projects', models.ManyToManyField(blank=True, help_text='Course projects', to='projects.project')),
            ],
        ),
    ]
